# Generated by Django 4.0.6 on 2022-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_bio_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email пользователя')),
                ('code', models.BinaryField(verbose_name='Код верификации')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Когда сгенерирован код ')),
            ],
        ),
    ]
